src/main/java/edu/wustl/mir/ctt/AEController.java
package edu.wustl.mir.ctt;

import edu.wustl.mir.ctt.form.AdverseEventWorksheetSAEForm;
import edu.wustl.mir.ctt.model.ECPEventTypes;
import edu.wustl.mir.ctt.model.ECPEvents;
import edu.wustl.mir.ctt.model.Event;
import edu.wustl.mir.ctt.model.EventStatus;
import edu.wustl.mir.ctt.model.FormStatus;
import edu.wustl.mir.ctt.model.Participant;
import edu.wustl.mir.ctt.model.Site;
import edu.wustl.mir.ctt.notification.NotificationContent;
import edu.wustl.mir.ctt.notification.NotificationException;
import edu.wustl.mir.ctt.notification.NotificationManager;
import edu.wustl.mir.ctt.notification.NotificationType;
import edu.wustl.mir.ctt.persistence.PersistenceException;
import java.io.Serializable;
import java.util.Calendar;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.component.UIOutput;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.event.ValueChangeEvent;
import javax.faces.validator.ValidatorException;

import edu.wustl.mir.ctt.persistence.ServiceRegistry;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import edu.wustl.mir.ctt.log.AuditLogger;
import org.apache.logging.log4j.LogManager;
import org.primefaces.context.RequestContext;
//import wsclient.WebServiceException_Exception;

@ManagedBean
@ViewScoped
public class AEController implements Serializable {
    private AdverseEventWorksheetSAEForm aeForm;
    private Participant participant;
    private int i = 0;
    private int j = 0;
    
    private AuditLogger logger;
    
    // The participant or patient id (pid) is a string of format xxxxxx and is not the participant table id 
    //which is an autogenerated integer returned by the enrollment webservice.
    private String pid = "";
    
    
    
    public boolean noTreatment;
    

    @ManagedProperty(value="#{controller}")
    private Controller controller;
    
    public AEController() {
        // initialization is moved to 'PostConstruct' because that
        // is when the injection is gauranteed to be complete.
        logger = AuditLogger.create(AEController.class);
    }
    
    @PostConstruct 
   protected void init() {
        if( controller.getSelectedForm() == null) {
            aeForm = new AdverseEventWorksheetSAEForm();
            aeForm.setCrfVersion(controller.getSelectedSite().getCrfVersion());
            aeForm.versionControl();
            logger.audit("Creating new SAE");
        } else {
            aeForm = (AdverseEventWorksheetSAEForm) controller.getSelectedForm();
            logger.audit("Loading existing SAE");
        }
//        aeForm.setReportType("initial");
        participant = controller.getSelectedParticipant();
        pid = participant.getParticipantID();
        
        logger.audit("Initiating SAE for " + pid);
        
        Calendar calendar = Calendar.getInstance();
        if(aeForm.getCurrentDate() == null){
            aeForm.setCurrentDate( calendar.getTime());
        }
        aeForm.setDateParticipantEnrollment(participant.getEnrolledDate());
        //aeForm.setMethoxsalen("");
    }
    

    public Controller getController() {
        return controller;
    }
    
    public void setController( Controller controller) {
        this.controller = controller;
    }
    
    public AdverseEventWorksheetSAEForm getAdverseEventWorksheetSAEForm() {
        return aeForm;
    }
    
    public void setAdverseEventWorksheetSAEForm(AdverseEventWorksheetSAEForm eform) {
        this.aeForm = eform;
    }
    
    public String getParticipantID() {
        // The participant or patient id (pid) is a string of format xxxxxx 
        // and is not the participant table id which is an autogenerated integer returned by the 
        // enrollment webservice.
        return pid;
    }
    
    public boolean isFormSummaryControlRendered() {
        return true;
    }
    
    public boolean isSourceDocControlRendered() {
        return true;
    }
    
    public boolean isSectionOneAttestationRendered() {
        return isAESectionComplete() && (! isSeriousAdverseEvent()) && ( ! isUnanticipatedProblem()) && ( ! isQualifyingSAE());
    }
    
    public boolean isSectionTwoAttestationRendered() {
        logger.audit("In isSectionTwoAttestationRendered, aeForm.isSAESectionComplete() value is: " + isSAESectionComplete());
        logger.audit("In isSectionTwoAttestationRendered, !isQualifyingSAE() value is: " + !isQualifyingSAE());
        logger.audit("In isSectionTwoAttestationRendered, !isUnanticipatedProblem() value is: " + !isUnanticipatedProblem() + " and count = " + i++ + "\n");
        return isSAESectionComplete() && ( !isQualifyingSAE()) && ( ! isUnanticipatedProblem());
    }

    // The following method renders AE/SAE Section 1
    public boolean isAESectionRendered() {
        return true;
    }

    // The following method renders AE/SAE Section 2
    public boolean isSAESectionRendered() {
        boolean isQualifyingSAE = isQualifyingSAE();
        boolean isSAE = isSeriousAdverseEvent();
        boolean isUP = isUnanticipatedProblem();
        if((isQualifyingSAE == false) && (isSAE == false) && (isUP == false)){
            // The RequestContext context in the reset below does not want to work in reseting the date/time if a p:ajax component is used in the calendar.
            resetSection2Items();
            // It appears the context reset does not work on the questions.  The RequestContext context is primefaces origin which may explain the not working issue.
            // Instead, the questions must be cleared.
            clearSection2Questions();
            clearSection3Questions();
        }
//        logger.audit("In isSAESectionRendered, getWasEventRelatedToUseECP value is: " + aeForm.getWasEventRelatedToUseECP());
//        logger.audit("In isSAESectionRendered, isSeriousAdverseEvent value is: " + isSAE);
//        logger.audit("In isSAESectionRendered, isUnanticipatedProblem value is: " + isUP + " and count = " + i++ + "\n");
        return  isQualifyingSAE || isSAE || isUP;
    }
    
    // The following method renders AE/SAE Section 3
    public boolean isSAEDetailSectionRendered() {
//        logger.audit("In isSAEDetailedSectionRendered, getWasEventRelatedToUseECP value is: " + aeForm.getWasEventRelatedToUseECP());
//        logger.audit("In isSAEDetailedSectionRendered, isQualifyingSAE value is: " + isQualifyingSAE());
//        logger.audit("In isSAEDetailedSectionRendered, isSAESectionRendered value is: " + isSAESectionRendered() + " and count = " + j++ + "\n");
        if (!(isQualifyingSAE() && isSAESectionRendered()) || (isUnanticipatedProblem() && isSAESectionRendered())){
            clearSection3Questions();
        }

        return (isQualifyingSAE() && isSAESectionRendered()) || (isUnanticipatedProblem() && isSAESectionRendered());
    }

        //================================================================================================
    // In Section 1 of the AE/SAE form, if you answer YES to Question 1 or 2 or 3 or any combination,
    // then the event is a Serious Adverse Event (SAE).  If the answer to Question 1 or 2 is YES,
    // then the SAE is a Qualifying event requiring Sections 1, 2 and 3 to be completed,
    // and the SAE should be submitted to Washington University.
    //
    // If you answer YES to one or more of the parts in Question 3 in Section 1, then the event
    // is an SAE, but may not be a Qualifying SAE.  Whether the event in Question 3 is a Qualifying
    // SAE depends on how you answer the questions in Section 2.
    //
    // In the isSeriousAdverseEvent method below, the getters for Questions 1, 2 and 3 in
    // Section 1 are listed.
    //================================================================================================
    public boolean isSeriousAdverseEvent() {
        if ("true".equals(aeForm.getSeriousInjury())) {
            return true;
        } else if ("true".equals(aeForm.getHospitalAdmission())) {
            return true;
        } else if ("true".equals(aeForm.getPregnancyAbortion())) {
            return true;
        } else if ("true".equals(aeForm.getCongenitalAnomaly())) {
            return true;
        } else if ("true".equals(aeForm.getCancerNeonateInfant())) {
            return true;
        } else if ("true".equals(aeForm.getAggressiveMedicalIntervention())) {
            return true;
        } else if ("true".equals(aeForm.getSeriouslyJeopardizedHealth())) {
            return true;
        } else if ("true".equals(aeForm.getEmergencyDepartmentVisit())) {
            return true;
        } else {
            return false;
        }
    }
    
    //================================================================================================
    // In Section 1 of the AE/SAE form, if you answer YES to Question 4, then the event is an
    // Unanticipated Problem, and must be reported to Washington University.  All three sections of
    // the Serious Adverse Event (SAE) must be completed and the SAE should be submitted to Washington 
    // University..
    //================================================================================================
    public boolean isUnanticipatedProblem() {
       return "true".equals(aeForm.getIsUnanticipatedProblem());
    }
    
    //================================================================================================
    // In Section 1 of the AE/SAE form, if you answer YES to either Question 1 or 2, then the event
    // is a Qualifying Serious Adverse Event (SAE) requiring Sections 1, 2 and 3 to be completed,
    // and the SAE should be submitted to Washington University.  
    //

src/main/webapp/recalc/calculator.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    
    <ui:composition template="../template/template.xhtml">
        <ui:define name="body">
            
            <h:form>
            <h:outputStylesheet library="css" name="ecpregistry.css" />
            
            <div id="#{controller.style.header}">
                <h3>Extracorporeal Photopheresis (ECP) for the Management of Progressive Bronchiolitis Obliterans Syndrome (BOS) in Medicare-Eligible Recipients of Lung Allografts</h3>
                <h2>Refractory BOS Participant Statistical Calculator</h2>
            </div>
            <br/>
            
            <h:outputLabel for="selectSite" value="Site: " />
            <h:selectOneListbox id="selectSite" value="#{reCalcController.site}" size="1" converter="#{reCalcController.siteConverter}">
                <f:selectItems value="#{reCalcController.sites}" var="site" itemLabel="#{site.name}" itemValue="#{site}"/>
                <f:ajax listener="#{reCalcController.selectSiteListener}" render="selectParticipant evaluations :results"/>
            </h:selectOneListbox>
            &nbsp;&nbsp;
            <h:outputLabel for="selectParticipant" value="Participant: " />
            <h:selectOneListbox id="selectParticipant" value="#{reCalcController.participant}" size="1" converter="#{reCalcController.participantConverter}">
                <f:selectItems value="#{reCalcController.participants}" var="participant" itemLabel="#{participant.participantID}" itemValue="#{participant}"/>
                <f:ajax listener="#{reCalcController.selectParticipantListener}" render="evaluations :results"/>
            </h:selectOneListbox>
            &nbsp;&nbsp;
            <h:outputLabel for="referenceDate" value="Reference Date: " />
            <p:calendar id="referenceDate" class="calendar" value="#{reCalcController.referenceDate}" mode="popup" showOn="button" showButtonPanel="false" pattern="MM/dd/yyyy" navigator="true" size="10" converter="strictDateTimeConverter" />
            <br/>
            <!--<h:panelGrid id="evaluations">-->
            <h:panelGroup id="evaluations">
                <!-- forEach is part of JSTL, which is evaluated before the page loads, allowing us to generate unique IDs for the elements below to prevent duplication after submit -->
                <!-- note that JSTL variables use $ references instead of # references -->
                <c:forEach var="eval" items="${reCalcController.inputEvaluations}" varStatus="status">
                <div class="datefevfvc">
                    <div class="date">
                        <b><h:outputText value="Date "/></b>
                        <p:calendar id="dateOfFEV1${status.index}" value="#{eval.date}" required="" requiredMessage="#{msgs.dateOfFEV1}" mode="popup" showOn="button" showButtonPanel="true" pattern="MM/dd/yyyy" navigator="true" size="10" converter="strictDateTimeConverter"/>
                    </div>
                    <div class="fev">
                        <b>FEV1 </b>
                        <h:inputText id="fev1${status.index}" value="#{eval.fev1}" size="3" required="false" requiredMessage="#{msgs.fev1}" validatorMessage="FEV1 ranges between 0 and 6.0">
                            <f:validateLongRange minimum="0" maximum="6"/>
                        </h:inputText>
                        liters
                    </div>
                </div>
                <div class="clear"></div> 
                <div>
                    <p:message for="dateOfFEV1${status.index}" />
                    <p:message for="fev1${status.index}" />
                </div>
                </c:forEach>
                <p:messages showDetail="true"/>
            </h:panelGroup>
            <!--</h:panelGrid>-->
            <br/>
            <h:commandButton value="Reset" action="#{reCalcController.resetCalculatorAction}" />&nbsp;
            <h:commandButton value="More PFTs" action="#{reCalcController.moreEvalsAction}" />&nbsp;
            <h:commandButton value="Calculate" action="#{reCalcController.eligibilityCalcAction}" />

            </h:form>
            
            <h:panelGroup id="results">
                <p>
                    <h:outputText value="Site Protocol Version: #{reCalcController.site.irbVersion}"/> <br/>
                    <h:outputText value="Eligibility Evaluation: #{reCalcController.calculator.studyEligibilityOutcome}" /> <br/>
                    <h:outputText value="Eligibility Reason: #{reCalcController.calculator.outcomeMessage}" /> <br/>
                    <h:outputText value="Slope: #{reCalcController.calculator.slope} (ml per 30 days)"/> <br/>
                    <h:outputText value="P-Value: #{reCalcController.calculator.PValue}"/>
                </p>

                <p:chart type="line" model="#{chartView.lineModel}" style="height:500px; width: 800px;" rendered="#{reCalcController.renderChart}"/>
            </h:panelGroup>
        </ui:define>
    </ui:composition>
    
</html>

src/main/webapp/recalc/calculatorTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title>ECP Trial Site Resources</title>
    </h:head>

    <h:body>

<!--        <div id="top" class="top">
            <ui:insert name="top">Top</ui:insert>
        </div>-->

        <div id="content" class="center_content">
            <ui:insert name="content">Content</ui:insert>
        </div>

    </h:body>

</html>

src/main/webapp/recalc/crossoverCalculator.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    
    <ui:composition template="../template/template.xhtml">
        <ui:define name="body">
            
            <h:form>
            <h:outputStylesheet library="css" name="ecpregistry.css" />
            
            <div id="#{controller.style.header}">
                <h3>Extracorporeal Photopheresis (ECP) for the Management of Progressive Bronchiolitis Obliterans Syndrome (BOS) in Medicare-Eligible Recipients of Lung Allografts</h3>
                <h2>Refractory BOS Crossover Statistical Calculator</h2>
            </div>
            <br/>
            
            <h:outputLabel for="selectSite" value="Site: " />
            <h:selectOneListbox id="selectSite" value="#{reCalcController.site}" size="1" converter="#{reCalcController.siteConverter}">
                <f:selectItems value="#{reCalcController.sites}" var="site" itemLabel="#{site.name}" itemValue="#{site}"/>
                <f:ajax listener="#{reCalcController.selectSiteListener}" render="selectParticipant evaluations :results"/>
            </h:selectOneListbox>
            &nbsp;&nbsp;
            <h:outputLabel for="selectParticipant" value="Participant: " />
            <h:selectOneListbox id="selectParticipant" value="#{reCalcController.participant}" size="1" converter="#{reCalcController.participantConverter}">
                <f:selectItems value="#{reCalcController.obsParticipants}" var="participant" itemLabel="#{participant.participantID}" itemValue="#{participant}"/>
                <f:ajax listener="#{reCalcController.selectObservationParticipantListener}" render="evaluations :results"/>
            </h:selectOneListbox>
            &nbsp;&nbsp;
            <h:outputLabel for="referenceDate" value="Reference Date: " />
            <p:calendar id="referenceDate" class="calendar" value="#{reCalcController.referenceDate}" mode="popup" showOn="button" showButtonPanel="false" pattern="MM/dd/yyyy" navigator="true" size="10" converter="strictDateTimeConverter" />
            <br/>
            <!--<h:panelGrid id="evaluations">-->
            <h:panelGroup id="evaluations">
                <!-- forEach is part of JSTL, which is evaluated before the page loads, allowing us to generate unique IDs for the elements below to prevent duplication after submit -->
                <!-- note that JSTL variables use $ references instead of # references -->
                <c:forEach var="eval" items="${reCalcController.inputEvaluations}" varStatus="status">
                <div class="datefevfvc">
                    <div class="date">
                        <b><h:outputText value="Date "/></b>
                        <p:calendar id="dateOfFEV1${status.index}" value="#{eval.date}" required="" requiredMessage="#{msgs.dateOfFEV1}" mode="popup" showOn="button" showButtonPanel="true" pattern="MM/dd/yyyy" navigator="true" size="10" converter="strictDateTimeConverter"/>
                    </div>
                    <div class="fev">
                        <b>FEV1 </b>
                        <h:inputText id="fev1${status.index}" value="#{eval.fev1}" size="3" required="false" requiredMessage="#{msgs.fev1}" validatorMessage="FEV1 ranges between 0 and 6.0">
                            <f:validateLongRange minimum="0" maximum="6"/>
                        </h:inputText>
                        liters
                    </div>
                </div>
                <div class="clear"></div> 
                <div>
                    <p:message for="dateOfFEV1${status.index}" />
                    <p:message for="fev1${status.index}" />
                </div>
                </c:forEach>
                <p:messages showDetail="true"/>
            </h:panelGroup>
            <!--</h:panelGrid>-->
            <br/>
            <h:commandButton value="Reset" action="#{reCalcController.resetCalculatorAction}" />&nbsp;
            <h:commandButton value="More PFTs" action="#{reCalcController.moreEvalsAction}" />&nbsp;
            <h:commandButton value="Calculate" action="#{reCalcController.crossoverCalcAction}" />

            </h:form>
            <h:panelGroup id="results">
                <p>
                    <h:outputText value="Enrollment Date: #{reCalcController.participant.enrolledDate}" /><br/>
                    <h:outputText value="Currently on Hold: #{reCalcController.participant.holdStatus}" /><br/>
                    <h:outputText value="Hold Start Date: #{reCalcController.participant.holdStartDate}" /><br/><br/>

                    <h:outputText value="Slope: #{reCalcController.crossoverCalculator.slope} (ml per 30 days)"/> <br/>
                    <h:outputText value="P-Value: #{reCalcController.crossoverCalculator.PValue}"/><br/><br/>
                    
                    <h:outputText value="Crossover Eligibility Evaluation: #{reCalcController.crossoverCalculator.eligibilityString}" /> <br/>
                    <h:outputText value="Crossover Eligibility Reason: #{reCalcController.crossoverCalculator.outcomeRule}" /> <br/>
                </p>
            </h:panelGroup>
            
            <!--<p:chart type="line" model="#{chartView.lineModel}" style="height:500px; width: 800px;" rendered="#{reCalcController.renderChart}"/>-->
                
        </ui:define>
    </ui:composition>
    
</html>

src/main/webapp/recalc/eligibilityCalc.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    
    <ui:composition template="../template/template.xhtml">
        <ui:define name="body">
            
            <h:form>
            <h:outputStylesheet library="css" name="ecpregistry.css" />
            
            <div id="#{controller.style.header}">
                <h3>Extracorporeal Photopheresis (ECP) for the Management of Progressive Bronchiolitis Obliterans Syndrome (BOS) in Medicare-Eligible Recipients of Lung Allografts</h3>
                <h2>Refractory BOS Participant Eligibility Calculator</h2>
            </div>
            <br/>
            
            <!--<h:outputLabel for="selectSite" value="Site: " />
            <h:selectOneListbox id="selectSite" value="#{reCalcController.site}" size="1" converter="#{reCalcController.siteConverter}">
                <f:selectItems value="#{reCalcController.sites}" var="site" itemLabel="#{site.name}" itemValue="#{site}"/>
                <f:ajax listener="#{reCalcController.selectSiteListener}" render="selectParticipant evaluations :results"/>
            </h:selectOneListbox>
            &nbsp;&nbsp;-->
            <h:outputLabel for="selectParticipant" value="Participant: " />
            <h:selectOneListbox id="selectParticipant" value="#{reCalcController.participant}" size="1" converter="#{reCalcController.participantConverter}">
                <f:selectItems value="#{reCalcController.participants}" var="participant" itemLabel="#{participant.participantID}" itemValue="#{participant}"/>
                <f:ajax listener="#{reCalcController.selectParticipantListener}" render="evaluations :results"/>
            </h:selectOneListbox>
            &nbsp;&nbsp;
            <h:outputLabel for="referenceDate" value="Reference Date: " />
            <p:calendar id="referenceDate" class="calendar" value="#{reCalcController.referenceDate}" mode="popup" showOn="button" showButtonPanel="false" pattern="MM/dd/yyyy" navigator="true" size="10" converter="strictDateTimeConverter" />
            <br/>
            <!--<h:panelGrid id="evaluations">-->
            <h:panelGroup id="evaluations">
                <!-- forEach is part of JSTL, which is evaluated before the page loads, allowing us to generate unique IDs for the elements below to prevent duplication after submit -->
                <!-- note that JSTL variables use $ references instead of # references -->
                <c:forEach var="eval" items="${reCalcController.inputEvaluations}" varStatus="status">
                <div class="datefevfvc">
                    <div class="date">
                        <b><h:outputText value="Date "/></b>
                        <p:calendar id="dateOfFEV1${status.index}" value="#{eval.date}" required="" requiredMessage="#{msgs.dateOfFEV1}" mode="popup" showOn="button" showButtonPanel="true" pattern="MM/dd/yyyy" navigator="true" size="10" converter="strictDateTimeConverter"/>
                    </div>
                    <div class="fev">
                        <b>FEV1 </b>
                        <h:inputText id="fev1${status.index}" value="#{eval.fev1}" size="3" required="false" requiredMessage="#{msgs.fev1}" validatorMessage="FEV1 ranges between 0 and 6.0">
                            <f:validateLongRange minimum="0" maximum="6"/>
                        </h:inputText>
                        liters
                    </div>
                </div>
                <div class="clear"></div> 
                <div>
                    <p:message for="dateOfFEV1${status.index}" />
                    <p:message for="fev1${status.index}" />
                </div>
                </c:forEach>
                <p:messages showDetail="true"/>
            </h:panelGroup>
            <!--</h:panelGrid>-->
            <br/>
            <h:commandButton value="Reset" action="#{reCalcController.resetCalculatorAction}" />&nbsp;
            <h:commandButton value="More PFTs" action="#{reCalcController.moreEvalsAction}" />&nbsp;
            <h:commandButton value="Calculate" action="#{reCalcController.eligibilityCalcAction}" />

            </h:form>
            
            <h:panelGroup id="results">
                <p style="font-size:large; font-weight:bold;">
                    <h:outputText value="Eligibility Evaluation: #{reCalcController.calculator.studyEligibilityOutcome}" />
                    <h:outputText value="#{reCalcController.calculator.outcomeRule}" rendered="#{!reCalcController.calculator.studyEligible}"/><br/>
                </p>
            </h:panelGroup>

        </ui:define>
    </ui:composition>
    
</html>